---
# environment details
default_interface: "{{ default_network | default('eth0') }}"
default_vm_image: "{{ default_image | default('ubuntu-16.04-amd64') }}"
default_vm_storage: "{{ vm_disk_size | default(92160) }}"
default_acng_bind_address: 0.0.0.0
default_os_families:
  ubuntu-16.04-amd64: debian
  ubuntu-14.04-amd64: debian

default_ubuntu_kernel: linux-generic
default_ubuntu_mirror_proxy: 'http://10.0.2.1:3142/'
default_ubuntu_mirror_hostname: archive.ubuntu.com
default_ubuntu_mirror_directory: /ubuntu

default_container_tech: "{{ container_tech | default('lxc') }}"

# IP address, or domain name of the TFTP server
tftp_server: "{{ ansible_host }}"
# tftp_ssh_key: ''  # user defined ssh key, used to access the host
tftp_port: 69
tftp_root_dir: /var/lib/tftpboot

# ipxe
ipxe_branch: master
ipxe_repo: https://github.com/ipxe/ipxe.git
# use instead for LLDP support
#ipxe_branch: lldp_noconfig
#ipxe_repo: https://github.com/antonym/ipxe.git
ipxe_source_dir: /usr/src/ipxe

images:
  ubuntu-16.04-amd64:
    image_type: "debian"
    image_os: "ubuntu"
    image-version: "xenial"
    image_kernel_options: "auto=true priority=critical"
    image_netboot_kernel_url: "http://archive.ubuntu.com/ubuntu/dists/xenial/main/installer-amd64/current/images/netboot/ubuntu-installer/amd64/linux"
    image_netboot_initrd_url: "http://archive.ubuntu.com/ubuntu/dists/xenial/main/installer-amd64/current/images/netboot/ubuntu-installer/amd64/initrd.gz"
  ubuntu-16.04-amd64-hwe:
    image_type: "debian"
    image_os: "ubuntu"
    image-version: "xenial"
    image_kernel_options: "auto=true priority=critical"
    image_netboot_kernel_url: "http://archive.ubuntu.com/ubuntu/dists/xenial-updates/main/installer-amd64/current/images/hwe-netboot/ubuntu-installer/amd64/linux"
    image_netboot_initrd_url: "http://archive.ubuntu.com/ubuntu/dists/xenial-updates/main/installer-amd64/current/images/hwe-netboot/ubuntu-installer/amd64/initrd.gz"
  ubuntu-14.04-amd64:
    image_type: "debian"
    image_os: "ubuntu"
    image_version: "trusty"
    image_kernel_options: "auto=true priority=critical"
    image_netboot_kernel_url: "http://archive.ubuntu.com/ubuntu/dists/trusty/main/installer-amd64/current/images/netboot/ubuntu-installer/amd64/linux"
    image_netboot_initrd_url: "http://archive.ubuntu.com/ubuntu/dists/trusty/main/installer-amd64/current/images/netboot/ubuntu-installer/amd64/initrd.gz"
  utility:
    image_type: "utility"
    image_os: "centos"
    image_version: "7"
    image_kernel_options: "nomodeset rd.writable.fsimg rd.shell enforcing=0"
    image_netboot_kernel_url: "http://images.squashible.com/images/ecopoiesis-utility-centos/vmlinuz"
    image_netboot_initrd_url: "http://images.squashible.com/images/ecopoiesis-utility-centos/initrd.img"
    image_netboot_rootfs_url: "http://images.squashible.com/images/ecopoiesis-utility-centos/rootfs.img"
